branches:
- name: 'main'
  prerelease: 'alpha'
  channel: 'core'
- name: 'rc-*'
  prerelease: 'rc'
  channel: 'core'
- name: 'release-*'
  channel: 'core'

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
