branches:
- name: 'main'
  channel: 'alpha'
  prerelease: 'alpha'
- name: 'rc-*'
  channel: 'rc'
  prerelease: 'rc'
- 'release-*'

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
