name: Release Cut

on: workflow_dispatch

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0 # TODO: Parameterize this
          fetch-tags: true
      - name: Semantic Release
        uses: leongyh/semantic-branch-for-release@main
        id: semantic-release
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          action: release-cut
      - name: echo outputs
        run: |
          echo next-version: ${{ steps.semantic-release.outputs.next-version }}
          echo previous-version: ${{ steps.semantic-release.outputs.previous-version }}
          echo previous-stable-version: ${{ steps.semantic-release.outputs.previous-stable-version }}
